export const languages = {
  af: { name: "Afrikaans", nativeName: "Afrikaans" },
  sq: { name: "Albanian", nativeName: "Shqip" },
  am: { name: "Amharic", nativeName: "አማርኛ" },
  ar: { name: "Arabic", nativeName: "العربية" },
  hy: { name: "Armenian", nativeName: "Հայերեն" },
  az: { name: "Azerbaijani", nativeName: "Azərbaycan" },
  eu: { name: "Basque", nativeName: "Euskara" },
  be: { name: "Belarusian", nativeName: "Беларуская" },
  bn: { name: "Bengali", nativeName: "বাংলা" },
  bs: { name: "Bosnian", nativeName: "Bosanski" },
  bg: { name: "Bulgarian", nativeName: "Български" },
  ca: { name: "Catalan", nativeName: "Català" },
  ceb: { name: "Cebuano", nativeName: "Cebuano" },
  zh: { name: "Chinese", nativeName: "中文" },
  hr: { name: "Croatian", nativeName: "Hrvatski" },
  cs: { name: "Czech", nativeName: "Čeština" },
  da: { name: "Danish", nativeName: "Dansk" },
  nl: { name: "Dutch", nativeName: "Nederlands" },
  en: { name: "English", nativeName: "English" },
  et: { name: "Estonian", nativeName: "Eesti" },
  fil: { name: "Filipino", nativeName: "Filipino" },
  fi: { name: "Finnish", nativeName: "Suomi" },
  fr: { name: "French", nativeName: "Français" },
  gl: { name: "Galician", nativeName: "Galego" },
  ka: { name: "Georgian", nativeName: "ქართული" },
  de: { name: "German", nativeName: "Deutsch" },
  el: { name: "Greek", nativeName: "Ελληνικά" },
  gu: { name: "Gujarati", nativeName: "ગુજરાતી" },
  ht: { name: "Haitian Creole", nativeName: "Kreyòl Ayisyen" },
  ha: { name: "Hausa", nativeName: "Hausa" },
  haw: { name: "Hawaiian", nativeName: "ʻŌlelo Hawaiʻi" },
  he: { name: "Hebrew", nativeName: "עברית" },
  hi: { name: "Hindi", nativeName: "हिन्दी" },
  hmn: { name: "Hmong", nativeName: "Hmong" },
  hu: { name: "Hungarian", nativeName: "Magyar" },
  is: { name: "Icelandic", nativeName: "Íslenska" },
  ig: { name: "Igbo", nativeName: "Igbo" },
  id: { name: "Indonesian", nativeName: "Bahasa Indonesia" },
  ga: { name: "Irish", nativeName: "Gaeilge" },
  it: { name: "Italian", nativeName: "Italiano" },
  ja: { name: "Japanese", nativeName: "日本語" },
  jv: { name: "Javanese", nativeName: "Basa Jawa" },
  kn: { name: "Kannada", nativeName: "ಕನ್ನಡ" },
  kk: { name: "Kazakh", nativeName: "Қазақ тілі" },
  km: { name: "Khmer", nativeName: "ខ្មែរ" },
  ko: { name: "Korean", nativeName: "한국어" },
  ku: { name: "Kurdish", nativeName: "Kurdî" },
  ky: { name: "Kyrgyz", nativeName: "Кыргызча" },
  lo: { name: "Lao", nativeName: "ລາວ" },
  la: { name: "Latin", nativeName: "Latina" },
  lv: { name: "Latvian", nativeName: "Latviešu" },
  lt: { name: "Lithuanian", nativeName: "Lietuvių" },
  lb: { name: "Luxembourgish", nativeName: "Lëtzebuergesch" },
  mk: { name: "Macedonian", nativeName: "Македонски" },
  mg: { name: "Malagasy", nativeName: "Malagasy" },
  ms: { name: "Malay", nativeName: "Bahasa Melayu" },
  ml: { name: "Malayalam", nativeName: "മലയാളം" },
  mt: { name: "Maltese", nativeName: "Malti" },
  mi: { name: "Maori", nativeName: "Māori" },
  mr: { name: "Marathi", nativeName: "मराठी" },
  mn: { name: "Mongolian", nativeName: "Монгол" },
  my: { name: "Myanmar (Burmese)", nativeName: "မြန်မာစာ" },
  ne: { name: "Nepali", nativeName: "नेपाली" },
  no: { name: "Norwegian", nativeName: "Norsk" },
  ny: { name: "Nyanja (Chichewa)", nativeName: "Chichewa" },
  or: { name: "Odia (Oriya)", nativeName: "ଓଡ଼ିଆ" },
  ps: { name: "Pashto", nativeName: "پښتو" },
  fa: { name: "Persian", nativeName: "فارسی" },
  pl: { name: "Polish", nativeName: "Polski" },
  pt: { name: "Portuguese", nativeName: "Português" },
  pa: { name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  ro: { name: "Romanian", nativeName: "Română" },
  ru: { name: "Russian", nativeName: "Русский" },
  sm: { name: "Samoan", nativeName: "Gagana Samoa" },
  gd: { name: "Scots Gaelic", nativeName: "Gàidhlig" },
  sr: { name: "Serbian", nativeName: "Српски" },
  st: { name: "Sesotho", nativeName: "Sesotho" },
  sn: { name: "Shona", nativeName: "Shona" },
  sd: { name: "Sindhi", nativeName: "سنڌي" },
  si: { name: "Sinhala", nativeName: "සිංහල" },
  sk: { name: "Slovak", nativeName: "Slovenčina" },
  sl: { name: "Slovenian", nativeName: "Slovenščina" },
  so: { name: "Somali", nativeName: "Soomaali" },
  es: { name: "Spanish", nativeName: "Español" },
  su: { name: "Sundanese", nativeName: "Basa Sunda" },
  sw: { name: "Swahili", nativeName: "Kiswahili" },
  sv: { name: "Swedish", nativeName: "Svenska" },
  tl: { name: "Tagalog", nativeName: "Tagalog" },
  tg: { name: "Tajik", nativeName: "Тоҷикӣ" },
  ta: { name: "Tamil", nativeName: "தமிழ்" },
  tt: { name: "Tatar", nativeName: "Татар" },
  te: { name: "Telugu", nativeName: "తెలుగు" },
  th: { name: "Thai", nativeName: "ไทย" },
  tr: { name: "Turkish", nativeName: "Türkçe" },
  tk: { name: "Turkmen", nativeName: "Türkmen" },
  uk: { name: "Ukrainian", nativeName: "Українська" },
  ur: { name: "Urdu", nativeName: "اردو" },
  ug: { name: "Uyghur", nativeName: "ئۇيغۇرچە" },
  uz: { name: "Uzbek", nativeName: `O'zbek` },
  vi: { name: "Vietnamese", nativeName: "Tiếng Việt" },
  cy: { name: "Welsh", nativeName: "Cymraeg" },
  xh: { name: "Xhosa", nativeName: "isiXhosa" },
  yi: { name: "Yiddish", nativeName: "ייִדיש" },
  yo: { name: "Yoruba", nativeName: "Yorùbá" },
  zu: { name: "Zulu", nativeName: "isiZulu" },
};
